### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by lirantal** [vincentmorneau/apex-publish-static-files#12]
Hello,

As a member of the [Node.js Security WG](https://hackerone.com/nodejs-ecosystem)
I would like to draw your attention to a security report that has been made regarding this package.

I have made attempts to contact the person identified as a maintainer of this package but did not get any answer. What is the best way to reach someone with commit rights over this repo and hopefully npm publishing rights as well, in order to invite them to privately discuss the issue on the HackerOne platform and provide a resolution? 

Thanks,
Liran

References:
* [Node.js Security WG ecosystem vulnerability processes](https://github.com/nodejs/security-wg/blob/master/processes/third_party_vuln_process.md)

**Comment by vincentmorneau** [comment]
I am the maintainer, so who did you contact first?

Please write to vincent.morneau@gmail.com with more details regarding the security report.

Thanks.

**Comment by lirantal** [comment]
Hi Vincent, thanks for the prompt reply on this.
I already invited that e-mail address. Can you look into your spam/inbox folder for invite e-mails from the HackerOne (or H1) platform?

**Comment by lirantal** [comment]
Thank you!
