### ISSUE TITLE
Option to publish a single file rather than all files in a directory

### ISSUE THREAD

**Issue by tim-lawson** [vincentmorneau/apex-publish-static-files#14]
Hi,

Firstly, thank you for your work on this to date. I work in a relatively large team of APEX developers and am looking at improvements to our workflow. To this end, I have begun work on a VSCode extension similar to @tschf's [odb-task](https://github.com/tschf/odb-task) that uses this package to publish static files.

One thing I noted was that it would be valuable to have the option to publish a single file rather than all files in a directory. Publishing all files at once has two drawbacks:

- Increased upload time
- May overwrite other developers' changes

I am not familiar with ~Java~ Node but I think a straightforward change to [distUpload.js](https://github.com/vincentmorneau/apex-publish-static-files/blob/master/lib/distUpload.js) would make this possible.

Thanks!

**Comment by vincentmorneau** [comment]
Hi @tslwn ,

I think it's a great idea and I am looking forward to your VSCode extension.

This project was developed to support APEX Nitro's publish feature, but I have no immediate plans to extend it.

I would be open to accept a pull request that does this if you are willing to contribute.

Thanks.

**Comment by tim-lawson** [comment]
Great! In that case I'll work on this first and submit a PR.
