### ISSUE TITLE
Help for a node/js beginner

### ISSUE THREAD

**Issue by JoseArostegui** [vincentmorneau/apex-publish-static-files#18]
Hi Vincent,

I've found your tool very interesting for developing a .xlsx template of AOP and uploading it quickly to "Shared Components\Static Application Files", but I'm not very experienced with node and npm and don't know how to make it work.

Could you please provide more details? 

So far:

1) mkdir e:\oracle\apex-publish-static-files
2) cd e:\oracle\apex-publish-static-files
3) npm install apex-publish-static-files
4) mkdir e:\oracle\apex-publish-static-files\upload-files
5) Copy my .xlsx template to e:\oracle\apex-publish-static-files\upload-files
6) Create a file "run.js":

var publisher = require('apex-publish-static-files');

publisher.publish({
    connectString: "pjm/xxxxxx@//myhost:1521/pdbapex",
    directory: "E:/oracle/apex-publish-static-files/upload-files",
    appID: 200
});   

7) execute it:
   node run.js
   
----------------
E:\oracle\apex-publish-static-files>node run.js
Uploading to 200 - Application Static Files...

SQLcl: Versi�n 19.1 Production en lun jul 06 17:52:56 2020

Copyright (c) 1982, 2020, Oracle. Todos los derechos reservados.

Conectado a:
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

Executing login.sql
Could not load file: &DIST_UPLOAD.

PJM@//myhost:1521/pdbapex>
Desconectado de Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

Files were uploaded successfully.
----------------

Thanks,
Jose.

**Comment by vincentmorneau** [comment]
Do you happen to know what is : `Executing login.sql` ?

**Comment by JoseArostegui** [comment]
It's my login.sql file (https://www.talkapex.com/2015/05/sqlcl-and-loginsql), oldschool sqlplus init script. 

I guess last "set scan off" was messing. If I avoid to execute it, your program works fine.

Thanks,
Jose.

```
set termout off
define gname=idle
column global_name new_value gname
select lower(user)||'@' ||substr(global_name,1,decode(dot,0,length(global_name),dot-1)) global_name from (select global_name, instr(global_name,'.') dot from global_name);

set sqlprompt '&gname>'
set termout on
set linesize 200
set pagesize 100

column VALUE_COL_PLUS_SHOW_PARAM format A65
column NAME_COL_PLUS_SHOW_PARAM  format A40

set sqlprompt "_user'@'_connect_identifier>"

script  
  var System  = Java.type("java.lang.System");  
  System.out.println("Executing login.sql");

/
set scan off
```
