### ISSUE TITLE
Command line runner

### ISSUE THREAD

**Issue by tschf** [vincentmorneau/apex-publish-static-files#2]
Might be a nice addition to supply a runnable command for the command line. 

I created a fork earlier on to give [this a go](https://github.com/tschf/apex-publish-static-files/tree/add-bin). I took example from another project (http-server), So that when I install (globally), it creates as link as per:

```
npm install -g
/home/trent/.npm_modules/bin/afpub -> /home/trent/.npm_modules/lib/node_modules/apex-publish-static-files/bin/apex-publish-static-files
```

Then gives me a runnable program:

```
trent@birroth:~/Projects/apex-publish-static-files$ type -a afpub
afpub is /home/trent/.npm_modules/bin/afpub
```

(The only thing I'm unsure of, is how this behaves on Windows, as the script (and the project I copied from) seems more designed for unix systems)

I called the exe `afpub` just so the name isn't so long. 

Sample:

```
trent@birroth:/tmp$ afpub --connectString vmtest/vmtest@//192.168.0.182/xe --sqlclPath sql --directory /tmp/vm2 --appID 100
Uploading to Shared Components - Application Static Files...

SQLcl: Release 4.2.0 Production on Tue Feb 28 22:20:12 2017

Copyright (c) 1982, 2017, Oracle.  All rights reserved.

Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

Uploading: /tmp/vm2/test2.txt
Uploading: /tmp/vm2/test.txt

SQL> 
Disconnected from Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

Files were uploaded successfully.
```

Anyway, I didn't log a PR incase you didn't want to add an exe; or so you can take my example to introduce your own implementation.

P.s. You're always coming out with some nice projects - this one included. Nice work. :+1:

**Comment by vincentmorneau** [comment]
For now I won't add an exe, because APEX Front-End Boost inherits this project and does the exe already using the `afeb publish` command. See https://github.com/OraOpenSource/apex-frontend-boost#publish-to-apex 

Maybe if the adoption rate of this project goes up, I'll look into it!

PS I think your exe implementation would work on Windows too.

**Comment by tschf** [comment]
Ah yeah, all good :)
